env_config:
#  env_id: "highway-fast-v0"
#  env_id: "merge-v0"
#  env_id: "roundabout-v0"
  env_id: "intersection-v1"
  lanes_count: 4
  vehicles_count: 50
  duration: 400
  simulation_frequency: 15
  policy_frequency: 1
  initial_spacing: 2

  observation:
    type: "Kinematics"

  other_vehicles_type: "highway_env.vehicle.behavior.IDMVehicle"
  vehicles_density: 1.0

  action:
    type: "DiscreteMetaAction"

  collision_reward: -1
  reward_speed_range: [ 20, 30 ]
  centering_position: [ 0.3, 0.5 ]

  screen_width: 600
  screen_height: 150
  scaling: 5.5
  show_trajectories: false
  render_agent: true
  offscreen_rendering: false

model_config:
  algorithm: "DQN"
  policy: "MlpPolicy"
  policy_kwargs:
    net_arch: [ 256, 256 ]
  learning_rate: 0.0005
  buffer_size: 15000
  learning_starts: 200
  batch_size: 32
  gamma: 0.8
  train_freq: 1
  gradient_steps: 1
  target_update_interval: 50
  verbose: 1
#  tensorboard_log: "highway_dqn/"

reward:
  step_num: 3
  duration: 1
  desired_speed: 20
  r_safe_w: 0.7
  r_speed_w: 0.2
  r_lateral_w: 0.1
  v2r_w: 0.1
  baseline_reward_w: 0.5

  discount_factor_max: 0.8
  discount_factor_min: 0.2
  velocity_unit: 20
  risk_max_for_tree: 1

  prediction_model: "linear_model"
  prediction_model_configs:
    linear_model_config: { }

  fitting_model: "polynomial"
  fitting_model_config:
    polynomial: { }

  behavior_configs:
    behaviors_list: [ "lateral_left","lateral_right","soft_accel","hard_accel","soft_decel","hard_decel" ]
#    behaviors_list: [ "lateral_left","lateral_right" ,"cruise"]
    scenarios:
      - name: "scenario_1"
        description: "左转巡航，后2秒保持轻加速"
        sequence:
          - lateral: "lateral_left"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_2"
        description: "右转巡航，后2秒保持轻加速"
        sequence:
          - lateral: "lateral_right"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_3"
        description: "左转巡航→左转轻加速→保持轻加速"
        sequence:
          - lateral: "lateral_left"
            longitudinal: "cruise"
          - lateral: "lateral_left"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_4"
        description: "右转巡航→右转轻加速→保持轻加速"
        sequence:
          - lateral: "lateral_right"
            longitudinal: "cruise"
          - lateral: "lateral_right"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_5"
        description: "前2秒巡航，第3秒左转轻加速"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_left"
            longitudinal: "soft_accel"

      - name: "scenario_6"
        description: "前2秒巡航，第3秒右转轻加速"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_right"
            longitudinal: "soft_accel"

      - name: "scenario_7"
        description: "3秒保持巡航"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "cruise"

      - name: "scenario_8"
        description: "3秒保持轻加速"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_9"
        description: "3秒保持轻刹车"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"

      - name: "scenario_10"
        description: "第1秒巡航，后2秒轻刹车"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"

      - name: "scenario_11"
        description: "第1秒轻加速，后2秒巡航"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "cruise"

      - name: "scenario_12"
        description: "第1秒重刹车，后2秒巡航"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "hard_decel"
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "cruise"

      - name: "scenario_13"
        description: "第1秒重刹车，后2秒轻加速"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "hard_decel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_14"
        description: "前2秒重刹车，第3秒轻加速"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "hard_decel"
          - lateral: "lateral_keep"
            longitudinal: "hard_decel"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"

      - name: "scenario_15"
        description: "轻加速→巡航→轻刹车（三阶段变化）"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"

      - name: "scenario_16"
        description: "巡航→轻刹车→重刹车（刹车力度递增）"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "soft_decel"
          - lateral: "lateral_keep"
            longitudinal: "hard_decel"

      - name: "scenario_17"
        description: "巡航→轻加速→重加速（加速力度递增）"
        sequence:
          - lateral: "lateral_keep"
            longitudinal: "cruise"
          - lateral: "lateral_keep"
            longitudinal: "soft_accel"
          - lateral: "lateral_keep"
            longitudinal: "hard_accel"

  riskmap_config:
    cell_size: 3

  # 可视化配置（riskmap)
  visualize: false # 是否创建可视化工具实例
  plt_show: false # 是否通过plt可视化

training:
  total_timesteps: 10000
  save_dir: "./agent"
#  render_mode: "human" # 不能和其他的图像显示器一起开启

test_config:
  model_path: "./agent/default_model"
  render_mode: "human" # 可选: "human", "rgb_array", null
  test_episodes: 1
# urm riskmap baseline
env_wrapper: "riskmap"
